version: 2.5.{build}
branches:
  only:
  - master
os: Visual Studio 2015
install:
- dnvm upgrade -r clr
- dnu restore
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
after_build:
- ps: 
test_script:
# doesn't appear to be an equivalent of 'copy local' - https://github.com/aspnet/dnx/issues/955
- copy C:\Users\appveyor\.dnx\packages\NUnit\2.6.4\lib\nunit.framework.dll artifacts\bin\Stateless.Tests\Release\net40\
- copy artifacts\bin\Stateless\Release\net40\stateless.dll artifacts\bin\Stateless.Tests\Release\net40\
- C:\Users\appveyor\.dnx\packages\NUnit.Runners\2.6.4\tools\nunit-console-x86.exe /config:Release artifacts\bin\Stateless.Tests\Release\net40\Stateless.Tests.dll
deploy:
- provider: NuGet
  api_key:
    secure: U0b7CQk3G8x+xfzoeGz3o26PyoR4G/DuuJ/G63mMrj+mgrDgV0/JA7/4fqqzO2eH
  on:
    branch: master
